# Generated by Django 3.1 on 2020-08-17 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('creator', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField()),
                ('name', models.CharField(max_length=255)),
                ('length', models.DecimalField(decimal_places=2, max_digits=6)),
                ('avgspeed', models.DecimalField(decimal_places=2, max_digits=6)),
                ('maxspeed', models.DecimalField(decimal_places=2, max_digits=6)),
                ('avgcadence', models.IntegerField()),
                ('maxcadence', models.IntegerField()),
                ('avgheartrate', models.IntegerField()),
                ('minheartrate', models.IntegerField()),
                ('maxheartrate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trkpt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lan', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('ele', models.DecimalField(decimal_places=2, max_digits=6)),
                ('time', models.DateTimeField()),
                ('distance', models.DecimalField(decimal_places=2, max_digits=6)),
                ('speed', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cadence', models.IntegerField()),
                ('heartrate', models.IntegerField()),
                ('trackid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acstracks_app.track')),
            ],
        ),
    ]
