# Generated by Django 3.1 on 2020-08-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acstracks_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='avgcadence',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='avgheartrate',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='maxcadence',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='maxheartrate',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='minheartrate',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
