# Generated by Django 3.1 on 2020-08-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acstracks_app', '0003_auto_20200819_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='filename',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
