# Generated by Django 3.1 on 2020-08-19 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acstracks_app', '0005_auto_20200819_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='profiel',
            new_name='profile',
        ),
    ]
