# Generated by Django 3.1 on 2020-08-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acstracks_app', '0007_track_timelength'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trkpt',
            name='cadence',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='trkpt',
            name='heartrate',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
