# Generated by Django 3.1 on 2020-08-25 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acstracks_app', '0008_auto_20200824_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trkpt',
            old_name='lan',
            new_name='lat',
        ),
    ]
