# Generated by Django 3.1 on 2020-08-30 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acstracks_app', '0009_auto_20200825_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='totalascent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='totaldescent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Trkpt',
        ),
    ]
