# Generated by Django 3.1 on 2020-09-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acstracks_app', '0010_auto_20200830_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='displayfilename',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='storagefilename',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='username',
            field=models.CharField(default='-', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together={('username', 'displayfilename')},
        ),
        migrations.RemoveField(
            model_name='track',
            name='filename',
        ),
    ]
