# Generated by Django 3.1 on 2020-10-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acstracks_app', '0011_auto_20200901_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='avgspeed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='track',
            name='created_date',
            field=models.DateTimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='track',
            name='length',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='track',
            name='maxspeed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='track',
            name='profile',
            field=models.CharField(default='Fiets', max_length=255),
        ),
        migrations.AlterField(
            model_name='track',
            name='timelength',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='track',
            name='totalascent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='track',
            name='totaldescent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
