# Generated by Django 3.1 on 2020-10-23 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acstracks_app', '0013_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together={('user', 'displayfilename')},
        ),
        migrations.RemoveField(
            model_name='track',
            name='username',
        ),
    ]
