# Generated by Django 3.1 on 2020-11-16 09:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acstracks_app', '0014_auto_20201023_1449'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Threshold',
            new_name='Preference',
        ),
    ]
