# Generated by Django 3.1 on 2020-11-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acstracks_app', '0015_auto_20201116_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='show_avgcadence',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='show_avgheartrate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='show_avgspeed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='show_maxspeed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='show_totalascent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='show_totaldescent',
            field=models.BooleanField(default=True),
        ),
    ]
