# Generated by Django 3.1 on 2020-11-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acstracks_app', '0016_auto_20201116_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='avgspeed',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='track',
            name='maxspeed',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6),
        ),
    ]
