# Generated by Django 3.1 on 2020-11-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acstracks_app', '0017_auto_20201125_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='totalascent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='track',
            name='totaldescent',
            field=models.IntegerField(default=0),
        ),
    ]
