# Generated by Django 3.1 on 2021-02-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acstracks_app', '0019_auto_20201125_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='publickey',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
