# Generated by Django 3.1 on 2021-02-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acstracks_app', '0020_track_publickey'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='maxspeedcappingfactor',
            field=models.DecimalField(decimal_places=2, default=1.25, max_digits=6),
        ),
    ]
