# Generated by Django 3.1 on 2021-03-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acstracks_app', '0021_preference_maxspeedcappingfactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='profile',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
