# Generated by Django 3.1 on 2021-05-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acstracks_app', '0024_remove_preference_gpx_contains_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='date_end',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='date_start',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='intermediate_points_selected',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='preference',
            name='order_selected',
            field=models.CharField(blank=True, default='created_date_descending', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='profile_filter',
            field=models.CharField(blank=True, default='All', max_length=255, null=True),
        ),
    ]
