# Generated by Django 3.1 on 2021-05-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acstracks_app', '0025_auto_20210514_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='statistics_type',
            field=models.CharField(blank=True, default='annual', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='date_end',
            field=models.CharField(blank=True, default='2021-05-14', max_length=255, null=True),
        ),
    ]
