# Generated by Django 3.1 on 2021-07-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acstracks_app', '0026_auto_20210514_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='best20',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='track',
            name='best30',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='track',
            name='best60',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='preference',
            name='date_end',
            field=models.CharField(blank=True, default='2021-07-09', max_length=255, null=True),
        ),
    ]
