# Generated by Django 3.1 on 2021-07-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acstracks_app', '0027_auto_20210709_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='force_recalculate',
            field=models.BooleanField(default=False),
        ),
    ]
