# Generated by Django 3.1 on 2021-07-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acstracks_app', '0028_preference_force_recalculate'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='show_download_gpx',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preference',
            name='show_intermediate_points',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='preference',
            name='date_end',
            field=models.CharField(blank=True, default='2021-07-18', max_length=255, null=True),
        ),
    ]
