# Generated by Django 3.1 on 2021-07-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acstracks_app', '0029_auto_20210718_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='public_track',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='preference',
            name='date_end',
            field=models.CharField(blank=True, default='2021-07-19', max_length=255, null=True),
        ),
    ]
