# Generated by Django 3.1 on 2021-07-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acstracks_app', '0030_auto_20210719_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='show_is_public_track',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='date_end',
            field=models.CharField(blank=True, default='2021-07-20', max_length=255, null=True),
        ),
    ]
