# Generated by Django 3.1 on 2021-08-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acstracks_app', '0032_auto_20210721_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='maxspeed_latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='track',
            name='maxspeed_longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='preference',
            name='date_end',
            field=models.CharField(blank=True, default='2021-08-26', max_length=255, null=True),
        ),
    ]
