# Generated by Django 3.1 on 2021-08-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acstracks_app', '0034_auto_20210826_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='best20_pointindex',
            new_name='best20_end_pointindex',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='best30_pointindex',
            new_name='best20_start_pointindex',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='best60_pointindex',
            new_name='best30_start_pointindex',
        ),
        migrations.AddField(
            model_name='track',
            name='best60_start_pointindex',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6),
        ),
    ]
