# Generated by Django 3.1.14 on 2022-07-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acstracks_app', '0037_auto_20220506_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='show_trackeffort',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='track',
            name='trackeffort',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='date_end',
            field=models.CharField(blank=True, default='2022-07-18', max_length=255, null=True),
        ),
    ]
