# Generated by Django 3.1.14 on 2022-08-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acstracks_app', '0038_auto_20220718_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='show_trackeffort_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='preference',
            name='date_end',
            field=models.CharField(blank=True, default='2022-08-18', max_length=255, null=True),
        ),
    ]
