# Generated by Django 4.1.5 on 2023-03-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acstracks_app', '0039_auto_20220818_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='backgroundimage',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='date_end',
            field=models.CharField(blank=True, default='2023-03-06', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='show_trackeffort',
            field=models.BooleanField(default=True),
        ),
    ]
