# Generated by Django 4.1.5 on 2023-03-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acstracks_app', '0041_alter_preference_backgroundimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='backgroundimage',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
