# Generated by Django 4.1.5 on 2023-03-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acstracks_app', '0045_alter_preference_backgroundimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='backgroundimage',
            field=models.FileField(blank=True, default=None, max_length=255, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='date_end',
            field=models.CharField(blank=True, default='2023-03-07', max_length=255, null=True),
        ),
    ]
