# Generated by Django 4.1.5 on 2023-03-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acstracks_app', '0046_alter_preference_backgroundimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='colorscheme',
            field=models.CharField(default='giro', max_length=12),
        ),
        migrations.AlterField(
            model_name='preference',
            name='date_end',
            field=models.CharField(blank=True, default='2023-03-22', max_length=255, null=True),
        ),
    ]
