# Generated by Django 4.1.5 on 2023-03-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acstracks_app', '0047_preference_colorscheme_alter_preference_date_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='show_backgroundimage',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='date_end',
            field=models.CharField(blank=True, default='2023-03-31', max_length=255, null=True),
        ),
    ]
