# Generated by Django 4.1.5 on 2024-05-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acstracks_app', '0050_preference_default_profile_alter_preference_date_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='maximum_heart_rate',
            field=models.DecimalField(decimal_places=0, default=175, max_digits=3),
        ),
        migrations.AddField(
            model_name='preference',
            name='resting_heart_rate',
            field=models.DecimalField(decimal_places=0, default=70, max_digits=3),
        ),
        migrations.AlterField(
            model_name='preference',
            name='date_end',
            field=models.CharField(blank=True, default='2024-05-20', max_length=255, null=True),
        ),
    ]
