# Generated by Django 4.1.5 on 2024-06-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acstracks_app', '0052_alter_preference_date_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='hrzone1',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='track',
            name='hrzone2',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='track',
            name='hrzone3',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='track',
            name='hrzone4',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='track',
            name='hrzone5',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
