# Generated by Django 5.0.9 on 2025-03-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acstracks_app', '0053_track_hrzone1_track_hrzone2_track_hrzone3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='hide_first_part',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='track',
            name='hide_last_part',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='track',
            name='show_cadence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='track',
            name='show_download_gpx',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='track',
            name='show_heartrate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='track',
            name='show_markers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='track',
            name='show_trackeffort_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='preference',
            name='date_end',
            field=models.CharField(blank=True, default='2025-03-25', max_length=255, null=True),
        ),
    ]
