# Generated by Django 5.0.9 on 2025-03-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acstracks_app', '0054_track_hide_first_part_track_hide_last_part_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='link_to_detail_page',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='show_cadence',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='show_download_gpx',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='show_heartrate',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='show_intermediate_points',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='show_trackeffort_public',
        ),
        migrations.AddField(
            model_name='preference',
            name='privacy_zone',
            field=models.DecimalField(decimal_places=0, default=2000, max_digits=6),
        ),
        migrations.AlterField(
            model_name='preference',
            name='date_end',
            field=models.CharField(blank=True, default='2025-03-27', max_length=255, null=True),
        ),
    ]
