# Generated by Django 5.0.9 on 2025-03-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acstracks_app', '0055_remove_preference_link_to_detail_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='publictrack_pointindex',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='preference',
            name='date_end',
            field=models.CharField(blank=True, default='2025-03-30', max_length=255, null=True),
        ),
    ]
