# Generated by Django 5.0.9 on 2025-07-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acstracks_app', '0056_track_publictrack_pointindex_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='timelength',
            new_name='movingduration',
        ),
        migrations.AlterField(
            model_name='preference',
            name='date_end',
            field=models.CharField(blank=True, default='2025-07-27', max_length=255, null=True),
        ),
    ]
