# Generated by Django 5.0.9 on 2025-07-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acstracks_app', '0057_rename_timelength_track_movingduration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='duration',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
