# Generated by Django 5.0.9 on 2026-08-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acstracks_app', '0058_track_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='publictrack_pointindex',
            new_name='publictrack_end_pointindex',
        ),
        migrations.AddField(
            model_name='track',
            name='publictrack_start_pointindex',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='preference',
            name='date_end',
            field=models.CharField(blank=True, default='2026-08-15', max_length=255, null=True),
        ),
    ]
